name: Release Go project

on:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Release
      run: GOPROXY=proxy.golang.org go list -m github.com/ipaymu/ipaymu-go-api@${{ github.event.release.tag_name }}
